import "server-only";
import type { PlanSnapshot, PhaseSnapshot } from "@/lib/schemas/plan";

const STATUS_BADGE: Record<PhaseSnapshot["status"], string> = {
  complete: "✓ Complete",
  active: "● Active",
  pending: "○ Pending",
};

function fmtItem(item: PhaseSnapshot["items"][number]): string {
  const tick = item.done ? "x" : " ";
  const evidence = item.evidence ? ` — _${item.evidence}_` : "";
  return `- [${tick}] (${item.priority}) ${item.label}${evidence}`;
}

function fmtPhase(phase: PhaseSnapshot): string {
  const items = phase.items.map(fmtItem).join("\n");
  return `## Phase ${phase.id} — ${phase.name} (${STATUS_BADGE[phase.status]})\n\n${items}`;
}

/**
 * Renders the canonical plan snapshot as a Markdown report suitable for
 * pasting into a Plan-refresh PR (template: `.github/PULL_REQUEST_TEMPLATE/planning-pr.md`).
 *
 * Output is deterministic given the same snapshot, so it diffs cleanly when
 * pasted into an updated `docs/DELIVERY_PLAN.md`.
 */
export function renderPlanReport(snapshot: PlanSnapshot): string {
  const phases = snapshot.phases.map(fmtPhase).join("\n\n---\n\n");
  const p = snapshot.portfolio;
  const portfolio = [
    `## Portfolio at a glance`,
    "",
    `- Managed products: **${p.repos}**`,
    `- Average readiness: **${p.averageReadiness}/100**`,
    `- Active blockers: **${p.openBlockers.total}** total (${p.openBlockers.P0} P0 · ${p.openBlockers.P1} P1 · ${p.openBlockers.P2} P2)`,
  ].join("\n");

  return [
    `# Plan refresh — derived from canonical state`,
    "",
    `> Generated by the Plan Refresh Engine at \`${snapshot.computedAt}\`.`,
    `> Source: \`src/lib/services/plan/snapshot.ts\`.`,
    "",
    portfolio,
    "",
    `---`,
    "",
    phases,
  ].join("\n");
}

/**
 * Compares two `PlanSnapshot`s and returns a compact summary of phase-status
 * transitions and item-status flips. Useful for the "what would change?" view
 * before opening a planning PR.
 */
export type PlanDiff = {
  readonly phaseStatusChanges: ReadonlyArray<{
    readonly phaseId: number;
    readonly from: PhaseSnapshot["status"];
    readonly to: PhaseSnapshot["status"];
  }>;
  readonly itemDoneFlips: ReadonlyArray<{
    readonly phaseId: number;
    readonly label: string;
    readonly from: boolean;
    readonly to: boolean;
  }>;
  readonly portfolioReadinessDelta: number;
  readonly blockerDelta: number;
};

export function diffPlan(prev: PlanSnapshot, next: PlanSnapshot): PlanDiff {
  type StatusChange = PlanDiff["phaseStatusChanges"][number];
  type DoneFlip = PlanDiff["itemDoneFlips"][number];
  const phaseStatusChanges: StatusChange[] = [];
  const itemDoneFlips: DoneFlip[] = [];
  const prevPhases = new Map(prev.phases.map((p) => [p.id, p] as const));
  for (const np of next.phases) {
    const pp = prevPhases.get(np.id);
    if (pp === undefined) continue;
    if (pp.status !== np.status) {
      phaseStatusChanges.push({ phaseId: np.id, from: pp.status, to: np.status });
    }
    const prevItems = new Map(pp.items.map((i) => [i.label, i] as const));
    for (const ni of np.items) {
      const pi = prevItems.get(ni.label);
      if (pi === undefined) continue;
      if (pi.done !== ni.done) {
        itemDoneFlips.push({
          phaseId: np.id,
          label: ni.label,
          from: pi.done,
          to: ni.done,
        });
      }
    }
  }
  return {
    phaseStatusChanges,
    itemDoneFlips,
    portfolioReadinessDelta: next.portfolio.averageReadiness - prev.portfolio.averageReadiness,
    blockerDelta: next.portfolio.openBlockers.total - prev.portfolio.openBlockers.total,
  };
}
